import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { healthCheck } from "./api/healthCheck";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await healthCheck();

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <h1>API Status: {data}</h1>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
